### PR TITLE
Add Visdom logging to TNT

### PR DESCRIPTION
**Pull request by alexsax**
Added the ability to log to [Visdom](https://github.com/facebookresearch/visdom/) (like Tensorboard, but better!). It is a port of [this repo](https://github.com/alexsax/pytorch-nice) to TNT. 

screen shot 2017-08-03 at 3 27 10 pm

This PR adds TNT support for the existing Visdom plots and includes an example that uses it for MNIST (above).

### CODE REVIEW

**Comment by soumith** [comment]
Thanks Sasha. I'm making you a maintainer of this repo, so that you can continue to take it forward as you see best. cc: @szagoruyko who is the current maintainer.

**Comment by alexsax** [comment]
Awesome, thank you! Looking forward to helping TNT grow :)

**Comment by szagoruyko** [comment]
@alexsax great stuff, thanks! if you want to help out with tnt, take a look at https://github.com/pytorch/tnt/pull/26 and https://github.com/szagoruyko/tnt/tree/hook2, we started changing hooks to be more like Keras callbacks which fit tnt better.

**Comment by chsasank** [comment]
Hey @alexsax,

Looks like I'm a bit late to reply on PR. Nevertheless, don't you think it's better to not include visdom in tnt's requirements?

We can import visdomloggers only if visdom is available like this:

```
#logger/__init__.py
try:
   from . import stuff
except ImportError:
   pass
```

**Comment by chsasank** [comment]
@alexsax BTW are you on pytorch slack. Let's chat at #tnt? I was/am interested in developing for tnt :).

**Comment by alexsax** [comment]
@szagoruyko  My pleasure! I will start changing the hooks to conform to the new standard. 

@chsasank Good point :) tnt probably shouldn't take a dependency on visdom unless it's specifically requested.

**Pull request merged**
