### PR TITLE
Add more datasets

### PR DESCRIPTION
**Pull request by chsasank**
Added:
* SplitDataset
* ConcatDataset

Made `load` an optional parameter in `ListDataset` so that it can be used as `TableDataset`.

Added `seed` to resample in `ShuffleDataset`

I don't understand why `elem_list` has to `torch.LongTensor` if tensor in `ListDataset` (see [here](https://github.com/pytorch/tnt/pull/15/commits/8fafb5520d624fe182267fc82f600c5cca44cfdc#diff-d4468c8c095acb0bd76eff37ee0159c0R39)). It seems pointless.

Sasank.

### CODE REVIEW

**Comment by soumith** [comment]
cc: @szagoruyko to review

**Comment by szagoruyko** [comment]
@chsasank looks good! can you add tests for the new datasets similar to https://github.com/torchnet/torchnet/blob/master/test/datasets.lua#L106 ?

**Comment by chsasank** [comment]
I'll add tests. 

Can you please comment on this: 

> I don't understand why elem_list has to torch.LongTensor if tensor in ListDataset (see here). It seems pointless.

I think we should remove this restriction and allow for any iterable with __getitem__

**Comment by szagoruyko** [comment]
@chsasank yes, we can probably do that, that's a legacy from lua torchnet.

**Comment by chsasank** [comment]
@szagoruyko Tests added.

**Comment by lberrada** [comment]
Hi, I believe `self.partition_cum_sizes = np.cumsum(self.partition_sizes)` should be moved after the block `# if partition sizes are fractions, convert to sizes:` to cover the case when the split is given with fractions (the fraction case is not covered by the tests above).

**Comment by chsasank** [comment]
Thanks @lberrada for catching that.
I fixed it and added an unit test for that.

**Comment by szagoruyko** [comment]
this is awesome! thanks @chsasank

**Pull request merged**
