### PR TITLE
Add hook 'on_update'

### PR DESCRIPTION
**Pull request by Jiaming-Liu**
This PR add a hook 'on_update' in the engine. This might be helpful for showing real time loss&acc update

### CODE REVIEW

**Comment by szagoruyko** [comment]
thanks - I am confused about the name of the PR and the commit, can you fix it?

**Comment by Jiaming-Liu** [comment]
Sure. What would be a good name?

**Comment by szagoruyko** [comment]
@Jiaming-Liu the correct name is `on_update`, it exist in lua torch https://github.com/torchnet/torchnet/blob/master/engine/optimengine.lua#L119

**Comment by szagoruyko** [comment]
thanks!

**Pull request merged**
